### ISSUE TITLE
Error Handeling 

### ISSUE THREAD

**Issue by Thatcooldevguy** [Thatcooldevguy/Gity#1]
There Has Been Some Known Errors in error handling,

Where it prints this.
\ File "Gity.py", line 66
    except IOError:
         ^
SyntaxError: invalid syntax

**Comment by surister** [comment]
You are using excepts statements outside a try/except construction.
example:
`try:
     1+x
  except TypeError:
        pass
`

**Comment by Thatcooldevguy** [comment]
Gity is shutdown for now (making a new one)

If you want to help: message me on discord at https://discord.gg/HSzUyjE

The new one is at: https://github.com/Thatcooldevguy/toolr

Thanks for your help!

@surister
